### ISSUE TITLE
Error: react-native-image-picker: NativeModule.ImagePickerManager is null.

### ISSUE THREAD

**Issue by Hassanjankhan** [react-native-community/react-native-image-picker#1403]
##NativeModule.ImagePickerManager is null.
## Summary

i installe the 
react-native-image-picker but got the error ativeModule.ImagePickerManager is null.
i search it since form last foure houre but did'nt any luck i search it in the following link but did't any help i do the same procedure but not solved folling are the links which i have searced.
[https://github.com/react-native-community/react-native-image-picker/issues/1146](url)
[https://stackoverflow.com/questions/57150681/react-native-nativemodule-imagepickermanager-is-null](url)
[https://stackoverflow.com/questions/57359054/react-native-image-picker-null-is-not-an-object-evaluating-imagepickermanager](url)
[https://github.com/react-native-community/react-native-image-picker/issues/1137](url)

## Environment info

"react": "16.13.1",
"react-native": "0.63.0",
"react-native-image-picker": "^2.3.3",

`react-native info` output:

ERROR    Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker
[Thu Jul 30 2020 03:06:20.400]  WARN     Require cycle: node_modules\react-native-maps\lib\components\MapView.js -> node_modules\react-native-maps\lib\components\MapPolygon.js -> node_modules\react-native-maps\lib\components\MapView.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Thu Jul 30 2020 03:06:20.401]  WARN     Require cycle: node_modules\react-native-maps\lib\components\MapView.js -> node_modules\react-native-maps\lib\components\Geojson.js -> node_modules\react-native-maps\lib\components\MapView.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Thu Jul 30 2020 03:06:20.402]  ERROR    Error: react-native-image-picker: NativeModule.ImagePickerManager is null. To fix this issue try these steps:
• Run `react-native link react-native-image-picker` in the project root.
• Rebuild and re-run the app.
• If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
• Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
* If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-image-picker
[Thu Jul 30 2020 03:06:20.402]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Thu Jul 30 2020 03:06:20.403]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by chexj** [comment]
Same errors.

**Comment by Hassanjankhan** [comment]
> i can solved it by opening a terminal and write 
> npx react-native run-android

.

> But how can i get this error actually my method to run the application is

1.**`npx react-native start`**  by starting the metro.

and then from android stuido in terminal i connect through

2. **` adb reverse tcp:8081 tcp:8081`** 

so i close the metro and install the _`npm i react-native-image-picker`_

and again run start the metro and connect it form android studio successfully but i got this **Error: react-native-image-picker: NativeModule.ImagePickerManager is null.**

after spending much time did't work. at last **i close the android studio and metro and run the application through the command
npx react-native run-android and it work and the error is resolved.**

**Comment by Zhigamovsky** [comment]
try type in terminal `killall -9 node`. This command kill all node processes which in background. And try to rerun app again.

**Comment by andredewaard** [comment]
I have the exact same error, linking the module and rebuilding the app doesnt seem to resolve the issue for me.
```
[Thu Sep 03 2020 13:11:32.626]  ERROR    Error: react-native-image-picker: NativeModule.ImagePickerManager is null. To fix this issue try these steps:
• Run `react-native link react-native-image-picker` in the project root.
• Rebuild and re-run the app.
• If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
• Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
* If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-image-picker
[Thu Sep 03 2020 13:11:32.626]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Thu Sep 03 2020 13:11:32.628]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

**Comment by Hassanjankhan** [comment]
i have the same issue while using react-native-image-picker in the expo.
