### ISSUE TITLE
testOnImmutable fails with java.lang.NullPointerException

### ISSUE THREAD

**Issue by sometimescasey** [react-native-community/react-native-image-picker#972]
### Description

`testOnImmutable()` in `ImageConfigTest.java` throws NPE at line 29: `ImageConfig updated = original.withOriginalFile(null);`. 

`withOriginalFile` has a @Nullable annotation for the parameter - but I think the subsequent line `String extension = MimeTypeMap.getFileExtensionFromUrl(original.getAbsolutePath());` causes NPE.

This test failure causes `gradlew build` or `gradlew assembleRelease` to fail on an app that uses this package.

### How to repeat issue and example

* Install react-native-image-picker per README instructions. 
* Import to app using `import ImagePicker from 'react-native-image-picker';`. Use in app (my example is [here](https://github.com/sometimescasey/notsquirrel/blob/fixCamera/App.js))
* Run `./gradlew build` or `./gradlew assembleRelease` from the android folder of the app

Will get the following error during build:

```
> Task :react-native-image-picker:testDebugUnitTest 

com.imagepicker.testing.media.ImageConfigTest > testOnImmutable FAILED
    java.lang.NullPointerException at ImageConfigTest.java:29

5 tests completed, 1 failed


FAILURE: Build failed with an exception.
```

### Solution

Opened PR #973 . I worked around using the following change in `ImageConfig.java` - please let me know if there's a better way to handle this:

```
    public @NonNull ImageConfig withOriginalFile(@Nullable final File original)
    {
        if (original != null) {
        //if it is a GIF file, always set quality to 100 to prevent compression
        String extension = MimeTypeMap.getFileExtensionFromUrl(original.getAbsolutePath());
        int quality = this.quality;
        if(extension.contains("gif")){
            quality = 100;
        }
    }

        return new ImageConfig(
                original, this.resized, this.maxWidth,
                this.maxHeight, quality, this.rotation,
                this.saveToCameraRoll
        );
    }
```

### Additional Information

* React Native version: 0.57.4
* Platform: Android
* Development Operating System: Ubuntu 18.04
* Dev tools: react-native-cli

**Comment by ARMATAV** [comment]
This needs to be merged in - for future reference this does not throw an error in debug mode and must be `./gradlew check`'d in order to find.

**Comment by vinayan3** [comment]
I've hit this as well. It'd be great if this can be merged. Thanks!

**Comment by emech-en** [comment]
I have the same issue

**Comment by vinayan3** [comment]
Any updates on merging this?

**Comment by janicduplessis** [comment]
Fixed in https://github.com/react-native-community/react-native-image-picker/commit/619902cc167f3c10dc6d0c9688f9b5702f128a22

**Comment by uniwisi** [comment]
![image](https://user-images.githubusercontent.com/22497458/58798132-64425180-8634-11e9-96c4-80370f92f21b.png)
![image](https://user-images.githubusercontent.com/22497458/58798159-74f2c780-8634-11e9-953b-28c3c76fb7dc.png)
       react-native:0.57.8
       react-native-imgae-picker: 0.28
I check the imageConfig.java file
![image](https://user-images.githubusercontent.com/22497458/58798297-d74bc800-8634-11e9-8ab1-820c5cdc4982.png)
please help

**Comment by ryantando** [comment]
@uniwisi Hi, have you solved that one? I'm having the same issue

**Comment by ShavaShav** [comment]
This issue still happens when attempting to build a APK. Not sure why it was closed. This library prevents my application from building:

```
> Task :react-native-image-picker:testDebugUnitTest

com.imagepicker.testing.ImagePickerModuleTest > testCancelTakingPhoto FAILED
    org.apache.tools.ant.BuildException
        Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException
            Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException
                Caused by: org.apache.maven.project.ProjectBuildingException
                    Caused by: org.apache.maven.project.ProjectBuildingException
                        Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException
                            Caused by: org.apache.maven.wagon.ResourceDoesNotExistException

com.imagepicker.testing.media.ImageConfigTest > testOnImmutable FAILED
    org.apache.tools.ant.BuildException
        Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException
            Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException
                Caused by: org.apache.maven.project.ProjectBuildingException
                    Caused by: org.apache.maven.project.ProjectBuildingException
                        Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException
                            Caused by: org.apache.maven.wagon.ResourceDoesNotExistException

com.imagepicker.testing.media.ImageConfigTest > testParsingOptions FAILED
    org.apache.tools.ant.BuildException
        Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException
            Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException
                Caused by: org.apache.maven.project.ProjectBuildingException
                    Caused by: org.apache.maven.project.ProjectBuildingException
                        Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException
                            Caused by: org.apache.maven.wagon.ResourceDoesNotExistException

com.imagepicker.testing.media.ImageConfigTest > testUseOriginal FAILED
    org.apache.tools.ant.BuildException
        Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException
            Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException
                Caused by: org.apache.maven.project.ProjectBuildingException
                    Caused by: org.apache.maven.project.ProjectBuildingException
                        Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException
                            Caused by: org.apache.maven.wagon.ResourceDoesNotExistException

com.imagepicker.testing.media.ImageConfigTest > testGetActualFile FAILED
    org.apache.tools.ant.BuildException
        Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException
            Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException
                Caused by: org.apache.maven.project.ProjectBuildingException
                    Caused by: org.apache.maven.project.ProjectBuildingException
                        Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException
                            Caused by: org.apache.maven.wagon.ResourceDoesNotExistException

5 tests completed, 5 failed

> Task :react-native-image-picker:testDebugUnitTest FAILED

FAILURE: Build failed with an exception.
```

**Comment by bsgbryan** [comment]
I am getting the same error as @ShavaShav.

My Env:

```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 47.23 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3
      System Images: android-29 | Google APIs Intel x86 Atom_64
      Android NDK: 19.0.5232133
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4 
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5
```

```
$ java -version 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
```

**Comment by bsgbryan** [comment]
# Follow up

I got this working. The steps I took were _(all from my project root)_:

1. `rm -rf $APP_HOME/android/build` _($APP_HOME=/Users/$USER/{wherever your app is})_
1. `rm -rf $APP_HOME/android/app/build` _(we have some custom Android modules)_
1. `rm -rf ./node_modules/`
1. `npm it` _(to install all project dependencies and run our tests)_
1. `npx react-native start` _(we use npx to avoid having to install global node modules)_
1. `npx react-native run-android --deviceId $DEVICE_ID`

I'm guessing that at some point something got out of sync. Blowing everything away and starting from scratch seems to have fixed the issue! 🤘

**Comment by spsaucier-bakkt** [comment]
@bsgbryan Unfortunately, that didn't fix it for me -- still getting the same 5 failed tests.

**Comment by tristanhcole** [comment]
+1

**Comment by sebinq** [comment]
+1 I'm not able to build an app to real device

**Comment by dammyson** [comment]
I am getting this same error on my own project as well

**Comment by bsgbryan** [comment]
I found that, with a device attached, setup for USB debugging, and listed in `add devices` simply running `react-native run-android` works _(no `--deviceId` flag)_. There is something about the `--deviceId` flag that causes problems.

While this certainly isn't a fix, I hope this helps you all test on devices!

**Comment by chirag04** [comment]
I randomly found this thread on flutter which apparently had the same issue: https://github.com/flutter/flutter/issues/48943#issuecomment-575014355

```
Jan 16: Maven has changed their access policies as of today: https://support.sonatype.com/hc/en-us/articles/360041287334
```

Flutter fixed it here: https://github.com/flutter/plugins/pull/2475. 

Looks like we need to bump roboelectric? cc @janicduplessis since you originally fixed the issue.

**Comment by Metuuu** [comment]
I checked the test logs and for me the error was that I had older Java version installed (8) than what was required (9).
```
java.lang.UnsupportedOperationException: Failed to create a Robolectric sandbox: Android SDK 29 requires Java 9 (have Java 8)
```
